### PR TITLE
Add dynamic key suffix functionality.

### LINKED ISSUE #5: Design considerations in dynamic keys
Hello, I'm considering moving a project from `sidekiq-throttler` to `sidekiq-throttled`. One thing that is holding me back is that `sidekiq-throttled` currently does not support dynamic keys, for example:

```
sidekiq_options throttle: { threshold: 20, period: 1.day, key: ->(user_id){ user_id } }
```

I'm happy to fork and submit a pull request, but before I do that I wanted to check in with you about how you were thinking about the design.

The `Threshold` and `Concurrency` strategy classes both support `count` and `reset!` methods that don't apply very well to a dynamic keys use-case. (I'm not sure if they can be implemented in a way that doesn't involve an in-memory cache.) Looks like `reset!` is called in `Strategy`, where `count` doesn't seem to referenced anywhere else in this repo.

How do you think I should proceed? Would it be acceptable to simply say `reset!` and `count` are not supported if you're using dynamic keys?

### PR DESCRIPTION
**Pull request by fhwang**
Resolves #5

### CODE REVIEW

**Comment by fhwang** [comment]
Rubocop issues seem to be unrelated to the changes I've made. I've tried to address them in #7 .

**Comment by ixti** [comment]
#7 merged. Please rebase this PR.

**Comment by ixti** [comment]
And I will take a look once again :D

**Comment by fhwang** [comment]
Just rebased and squashed. Looking forward to your review!

**Comment by ixti** [comment]
Awesome! Thanks.

First of all, I guess key suffixer should be passed as a block to strategies. Not sure yet -- need to think about this a little bit more. In fact your PR raised couple of things I guess should be changed in sidekiq-throttled completely:
1. base prefix `sidekiq-throttled` of redis keys should be configurable
2. strategy prefixes should be shortened, e.g. `:c` instead of `:concurrency`

So the idea is to shorten useless info in keys.

Second thing I realized, dynamic keys can be shown in the UI. We can use `keys` redis command to grab all keys by mask `sidekiq-throttled:concurrency:{key}:*`. Also it's possible to get list of args of a proc:

``` ruby
->(x, y = nil) { }.parameters
# => [[:req, :x], [:opt, :y]]
```

So, in UI we can show such keys as `foobar(x, y)`. Not sure how useful that might be, probably some asterisk or other notification that strategy uses dynamic keys will be enough. For example dynamic and non-dynamic strategies can be in two separate groups in UI. And when you click on dynamic strategy it will bring you to list of active keys. Just an idea...

`each_with_static_key` IMO should be written (dirty sample) as:

``` ruby
@strategies.each { |name, strategy| yield strategy unless strategy.dynamic? }
```

**Comment by fhwang** [comment]
I think of dynamic keys as a bit of an edge case, so I didn't want to make it the block you pass to a strategy when instantiating. To me that implies that it's more central to the design than is warranted.

As for showing dynamic keys in the UI: The Redis docs themselves say to avoid using `keys` in production, so I didn't want to depend on that. There is `scan` as of Redis 2.8, so we could use that, though it's possible not all users will have a Redis that can support that.

I can change `each_with_static_key`, sure.

**Comment by fhwang** [comment]
Oh, also, regarding base prefixes, I guess I don't have a strong opinion on that one. I can see the desire for fully customizable keys, but it's current behavior is pretty convenient. Also, I can only think of two use-cases for wanting to customize keys, and with this PR they're both satisfied:
1. Having multiple job classes use the same strategy -- that was handled above the strategies, in `Registry`
2. Having the same job class use multiple key spaces -- that's handled in this PR.

Maybe there's another use case I'm not aware of, but if nothing comes up, personally I'd just leave it be for now.

**Comment by fhwang** [comment]
And does this coveralls result make any sense to you? I can't find any file that I touched that seems to get worse.

**Comment by ixti** [comment]
Coveralls report makes sense, but it's insignificant.
Sorry for delay, I will review everything and will merge this PR on the weekend.

**Comment by ixti** [comment]
Generally coveralls coverage went down by 0.3% because jruby test fails (was before this PR), and as the overall amount of lines changed, amount of covered VS uncovered (all files are uncovered for jruby) changed. :D

Thanks again for your PR. Merged it and released as 0.2.0.

Would like to note though that I plan to change `:key_suffix` to `:key` in some later releases.

**Comment by fhwang** [comment]
You're welcome! And a change to `:key` sounds fine to me FWIW.

**Pull request merged**
