### PR TITLE
fix: DRY-up job class/args extraction

### PR DESCRIPTION
**Pull request by ixti**
Related-PR: https://github.com/ixti/sidekiq-throttled/pull/184

### CODE REVIEW

**Comment by ixti** [comment]
cc: @jlledom

**Review by freemanoid — APPROVED** [review]
LCTM

**Review by jlledom — COMMENTED** [review]
Works fine for me. 👍

**Comment by mnovelo** [comment]
Sidekiq::Pro specs pass too!

**Comment by jeffbax** [comment]
Pardon the crudeness of the example, but I had noticed a similar situation to #184 attempting to adopt this gem over the past week or so (~moving from https://github.com/veeqo/activejob-uniqueness~) although this is for using the `threshold` strategy not the `concurrency` one.

`ERROR: Failed to get key suffix: wrong number of arguments (given 1, expected 2+)`

basically when I substitute

```
key_suffix: ->(args) do
  puts args
  raise
end
```

My output is 
```
 {
   "job_class" => "Events::JobKlass", 
   "job_id" => "abaccc09-9916-4ca4-9765-77968d09bbde", 
   "provider_job_id" => nil, 
   "queue_name" => "data_queue_low", 
   "priority" => nil, 
   "arguments" => ["Events::SavedEvent", { "id" => 307, "status_id_changes" => [1, 2], "_aj_symbol_keys" => [] }], 
   "executions" => 0, 
   "exception_executions" => {}, 
   "locale" => "en", 
   "timezone" => "Eastern Time (US & Canada)", 
   "enqueued_at" => "2024-03-28T18:14:14Z", 
   "first_enqueued_at" => 1711649654,
 }
```

Whereas I was _expecting_ to get the position arguments from the `arguments` key:
* "Events::SavedEvent"
* { "id" => 307, "status_id_changes" => [1, 2], "_aj_symbol_keys" => [] }

Is this an incorrect assumption on my part or perhaps a similar snag?

**Comment by ixti** [comment]
Will finish this PR and cut patch release this week.

**Comment by ixti** [comment]
Released as [v1.4.0](https://github.com/ixti/sidekiq-throttled/compare/v1.3.0...v1.4.0)

**Comment by jeffbax** [comment]
> Released as [v1.4.0](https://github.com/ixti/sidekiq-throttled/compare/v1.3.0...v1.4.0)

thanks! will give it a shot :)

**Pull request merged**
