### PR TITLE
FIX: Seems latest sidekiq do not use unique anymore

### PR DESCRIPTION
**Pull request by palanglung**
Latest Sidekiq versions i use does not use `@unique_queues` anymore instead the make `@queues` always unique.

### CODE REVIEW

**Comment by palanglung** [comment]
should i add sidekiq 4.1? to the gemfiles?

**Comment by ixti** [comment]
Oh. Thanks for catching this. In fact it's not defining uniq queues since `4.0`.

**Comment by ixti** [comment]
Oh. I have incorrectly read sidekiq sources. You're totally right. It's since 4.1

**Comment by ixti** [comment]
More than that, underlying logic was changed (TIMEOUT injected into queues)

**Comment by ixti** [comment]
Will need to add more specs for throttled fetcher in order cover all possible cases.

**Comment by ixti** [comment]
I have added extra gemfiles for appraisal. If you feel frisky, you are very welcome to extend specs and I believe we need to fix `@queues` list in general... If not I will do that later and will push new release.

**Comment by ixti** [comment]
https://github.com/sensortower/sidekiq-throttled/commit/4251a142a141be9003c41cc6eac9e661f5368813 -- this patch shows off existing issue

**Pull request merged**
