### PR TITLE
Add observe function

### PR DESCRIPTION
**Pull request by ogins57**
discussed in #47

### CODE REVIEW

**Comment by bnekolny** [comment]
any chance of this getting merged?

**Comment by ixti** [comment]
Thanks for reminder. Will take care of this during this week.

**Comment by bnekolny** [comment]
Just checking in on this one, any chance of a merge and release of a new version?

**Comment by ixti** [comment]
Merged and released as v0.11.0

**Comment by ixti** [comment]
Notice that I've changed `:observe` option name to `:observer` though.

**Pull request closed without merging**
