### PR TITLE
Don't replace :key_suffix

### PR DESCRIPTION
**Pull request by iporsut**
This change is [Reviewable](https://reviewable.io/reviews/sensortower/sidekiq-throttled/24)

### CODE REVIEW

**Comment by ixti** [comment]
Can you, please, add specs for this?

**Comment by iporsut** [comment]
I added spec but, I don't know why travis-ci fail.

**Comment by ixti** [comment]
I'll take a look today, thanks! Will merge/release today :D

**Comment by ixti** [comment]
Merged in as https://github.com/sensortower/sidekiq-throttled/commit/418772d6fcc959023c4d995320b71a9a435f1d35

**Comment by ixti** [comment]
Thank you. Specs are still broken (but those are kinda legit errors -- errors are not related to code but to specs themselves -- will fix it later)

**Pull request closed without merging**
